[worker] respect retention policy for pre-flight invocations (#5230)
Killing inboxed or scheduled invocations used to immediately delete the invocation irrespective of its completion and journal durations (both in vqueue and pre-vqueue world). This can be confusing to users as after canceling such invocations, they'll see them disappear from the UI without retaining their status.

This PR introduces a new experimental flag and a partition feature that once enabled, starts respecting completion and journal retention for those invocations.


*Test Plan*:

Before:

```

~/repos/restate/restate-cluster ❯❯❯ curl -X POST "localhost:8080/Counter/mbassem/add/send?delay=1h" --json 1                                                     ✘ 130 main ✱ ◼
{"invocationId":"inv_1bNhetDrexeA3AFcX2hgN6bxQr6rhpdO3J","executionTime":"2026-08-25T14:02:59.763000000Z","status":"Accepted"}%                                                 ~/repos/restate/restate-cluster ❯❯❯ restate inv get inv_1bNhetDrexeA3AFcX2hgN6bxQr6rhpdO3J | head                                                                      main ✱ ◼

~/repos/restate/restate-cluster ❯❯❯ restate inv kill inv_1bNhetDrexeA3AFcX2hgN6bxQr6rhpdO3J                                                                            main ✱ ◼
 ID                                      TARGET
 inv_1bNhetDrexeA3AFcX2hgN6bxQr6rhpdO3J  Counter/mbassem/add

✔ Are you sure you want to kill these invocations? · yes

✅ Killed 1 invocations
~/repos/restate/restate-cluster ❯❯❯ restate inv get inv_1bNhetDrexeA3AFcX2hgN6bxQr6rhpdO3J                                                                             main ✱ ◼
Error: Invocation inv_1bNhetDrexeA3AFcX2hgN6bxQr6rhpdO3J not found!

```

After:

```
❯❯❯ curl -X POST "localhost:8080/Counter/mbassem/add/send?delay=1h" --json 1                                                     ✘ 130 main ✱ ◼
{"invocationId":"inv_1bNhetDrexeA0gwrqDp8Sdxn7hJgfJLJ0c","executionTime":"2026-08-25T14:21:22.618000000Z","status":"Accepted"}

❯❯❯ restate inv kill inv_1bNhetDrexeA0gwrqDp8Sdxn7hJgfJLJ0c                                                                            main ✱ ◼
 ID                                      TARGET
 inv_1bNhetDrexeA0gwrqDp8Sdxn7hJgfJLJ0c  Counter/mbassem/add

✔ Are you sure you want to kill these invocations? · yes

✅ Killed 1 invocations
~/repos/restate/restate-cluster ❯❯❯ restate inv get inv_1bNhetDrexeA0gwrqDp8Sdxn7hJgfJLJ0c                                                                             main ✱ ◼

📜 Invocation Information:
――――――――――――――――――――――――――
 Created at:       2026-08-25 14:21:22.618 +01:00 (14 seconds ago)
 Target:           Counter/mbassem/add
 Status:           completed with failure
 Idempotency key:  01M0WHA9NTPVDQGQDSA9QVR9YZ
 Error:            [409] killed
 Modified at:      2026-08-25 14:21:28.449 +01:00


🚂 Invocation Progress:
―――――――――――――――――――――――
[Ingress]
 └──(this)─> Counter/mbassem/add
     ▸
     ├──── #0 [2026-08-25 14:21:22.618 +01:00] Command: Input
     └────>> completed
```

NOTE: I'm currently assuming this to be a 1.8 flag, but main is still on 1.7.7. I'll update depending on when this gets reviewed and whether we'll have a 1.7.8