Disable Github attestations
This commit disables the Github attestations because it recently failed
reliably with

Error: Failed to get ID token: Error message: Failed to get ID Token.

We can think about re-enabling it once we have figured out what's causing
the action to get the ID token.